Supplier admin temp
kaaylabs-v2/fleetmatch-admin pull request #12
Opened 2023-07-31 12:58 UTC by Deepakkumar-kaaylabs

2023-07-31 15:20 UTC, MJyotheesh commented on src/styles/supplier.scss
> +        }
images or svgs don't import in scss files

2023-07-31 15:20 UTC, MJyotheesh commented on src/styles/supplier-details.scss
> +            }
images or svgs don't import in scss files

2023-07-31 15:23 UTC, MJyotheesh commented on src/styles/lookups.scss
> +    font-family: "Montserrat",sans-serif;
font family give it common

2023-07-31 15:41 UTC, MJyotheesh commented on src/pages/supplier/supplier-profile.tsx
> +      const data = await getSupplier({ supplierUid, userType: 'admin' });
get role from const file

2023-07-31 15:42 UTC, MJyotheesh commented on src/pages/supplier/supplier-profile.tsx
> +    return ()=>{}
no use of returning empty object

2023-07-31 15:47 UTC, MJyotheesh commented on src/pages/supplier/supplier-datail-list.tsx
> +        <Accordion activeKey={collapse ? "1" : ""}>
Accordian was repeating most of the places can we make it as generic

2023-07-31 16:01 UTC, MJyotheesh commented on src/pages/supplier/index.tsx
> +      if (data.result.length) {
grt

2023-07-31 16:02 UTC, MJyotheesh commented on src/pages/supplier/index.tsx
> +      <div className="row m-0" style={{ height: "93%" }}>
inline

2023-07-31 16:08 UTC, MJyotheesh commented on src/pages/driver/index.tsx
> +      setDriverData(res.result);
get

2023-07-31 16:08 UTC, MJyotheesh commented on src/pages/driver/index.tsx
> +      const res = await getDriversList({status:activeTab,userType:'admin'})
get from const file

2023-07-31 16:09 UTC, MJyotheesh commented on src/pages/machinery/index.tsx
> +  );
spinner make it as generic

2023-07-31 16:09 UTC, MJyotheesh requested changes
Resolve comments

2023-07-31 16:55 UTC, Deepakkumar-kaaylabs commented on src/shared/constant-values.ts
> +export const mobileScreenWidth = 500;
ok changed

2023-08-01 00:59 UTC, Deepakkumar-kaaylabs commented on src/pages/supplier/supplier-datail-list.tsx
> +        <Accordion activeKey={collapse ? "1" : ""}>
will try

2023-08-01 01:00 UTC, Deepakkumar-kaaylabs commented on src/pages/supplier/supplier-details.tsx
> +        }}
I am using the same file for the driver and vehicle so I need to pass that from the parent only.

2023-08-03 11:52 UTC, closed without merging