Supplier admin
kaaylabs-v2/fleetmatch-admin pull request #14
Opened 2023-08-03 08:31 UTC by Deepakkumar-kaaylabs

2023-08-03 18:10 UTC, MJyotheesh commented on src/styles/supplier.scss
> +        }
images or svgs don't import in scss files

2023-08-03 18:11 UTC, MJyotheesh commented on src/styles/supplier-details.scss
> +    }
images or svgs don't import in scss files

2023-08-03 18:15 UTC, MJyotheesh commented on src/styles/loginPage.scss
Change file name as login-page.scss

2023-08-03 18:18 UTC, MJyotheesh commented on src/shared/meta-data/lookups.ts
> +      notificationMessage:"Lookup Value Added Successfully"
get from const validationMessages

2023-08-03 18:18 UTC, MJyotheesh commented on src/shared/meta-data/lookups.ts
> +      notificationMessage: "Lookup Value Updated Successfully"
get from const validationMessages

2023-08-03 18:18 UTC, MJyotheesh commented on src/shared/meta-data/lookups.ts
> +      notificationMessage: "Lookup value Deleted Successfully"
get from const validationMessages

2023-08-03 18:18 UTC, MJyotheesh commented on src/shared/meta-data/lookups.ts
> +      notificationMessage: "Lookup Created Succussfully"
get from const validationMessages

2023-08-03 18:19 UTC, MJyotheesh commented on src/shared/meta-data/index.ts
> +export { lookups, supplierList };
give one line space after the imports in all the places

2023-08-03 18:20 UTC, MJyotheesh commented on src/shared/icon-helper/index.tsx
why unused lines?

2023-08-03 18:21 UTC, MJyotheesh commented on src/shared/constant-values.ts
> +export const statusList = ["Approved", "Rejected", "Unapproved"];
use any one method right

2023-08-03 18:21 UTC, MJyotheesh commented on src/shared/constant-values.ts
> +export const mobileScreenWidth = 500;
570px

2023-08-03 18:21 UTC, MJyotheesh commented on src/pages/supplier/supplier-profile.tsx
> +      setSupplierData(data.result[0]);
get

2023-08-03 18:22 UTC, MJyotheesh commented on src/pages/supplier/supplier-profile.tsx
> +};
move all types to types.ts file (Refer supplier web)

2023-08-03 18:23 UTC, MJyotheesh commented on src/pages/supplier/supplier-profile.tsx
> +} = supplierList;
declare after imports

2023-08-03 18:29 UTC, MJyotheesh commented on src/pages/supplier/supplier-details.tsx
> +      {mobileScreenWidth>=window.innerWidth && <NavLink to='/supplier'>Back</NavLink>}
window.innerwidth declare in App.tsx and use it like this

useEffect(() => {
    const windowWidth = get(window, "innerWidth", 0);
    if (windowWidth < mobileScreenWidth) {
      dispatch(actions.setMobileView(true));
      setMobileView(true);
    } else {
      dispatch(actions.setMobileView(false));
      setMobileView(false);
    }
  }, []);

2023-08-03 18:31 UTC, MJyotheesh commented on src/pages/supplier/index.tsx
> +    setisMobile(mobileScreenWidth >= window.innerWidth);
move to app.tsx

2023-08-03 18:32 UTC, MJyotheesh commented on src/pages/supplier/index.tsx
> +import { Spinner, TitleWithSearch } from "../../components/generics";
TitleSearch

2023-08-03 18:33 UTC, MJyotheesh commented on src/pages/lookups/index.tsx
> +        <TitleWithSearch
TitleSearch

2023-08-03 18:34 UTC, MJyotheesh commented on src/pages/driver/index.tsx
> +      setDriverData(res.result);
get

2023-08-03 18:35 UTC, MJyotheesh requested changes
Resolve Comments

2023-08-04 06:19 UTC, Deepakkumar-kaaylabs commented on src/pages/driver/index.tsx
> +      setDriverData(res.result);
we are not using lodash in admin-web

2023-08-04 06:28 UTC, MJyotheesh commented on src/pages/driver/index.tsx
> +      setDriverData(res.result);
Not lodash refer supplier web for get function

2023-08-04 08:20 UTC, Deepakkumar-kaaylabs commented on src/styles/supplier.scss
> +        }
In accordion, this is the only way to change the collapse button , as we discussed will create custom accordion component then will remove this import bro

2023-08-06 12:52 UTC, Deepakkumar-kaaylabs commented on src/pages/supplier/supplier-details.tsx
> +      {mobileScreenWidth>=window.innerWidth && <NavLink to='/supplier'>Back</NavLink>}
We are not implemented redis in admin once we done that will change it

2023-08-06 13:36 UTC, MJyotheesh commented on src/pages/supplier/supplier-details.tsx
> +      {mobileScreenWidth>=window.innerWidth && <NavLink to='/supplier'>Back</NavLink>}
U can copy from supplier web right

2023-08-07 06:50 UTC, MJyotheesh approved these changes

2023-08-07 06:51 UTC, merged