loginfirstcommit
kaaylabs-v2/fleetmatch-admin pull request #3
Opened 2023-07-20 09:24 UTC by AravindKaay

Login Functionality is working

2023-07-20 12:58 UTC, MJyotheesh commented on src/components/button.tsx
> +};
give one line space after types

2023-07-20 12:58 UTC, MJyotheesh commented on src/components/button.tsx
> +};
here too

2023-07-20 13:02 UTC, MJyotheesh commented on src/components/index.tsx
> +export { Wrapper, SideMenu,InputComponent,ButtonComponent };
create generics folder in components then move button and input components there

2023-07-20 13:03 UTC, MJyotheesh commented on src/components/input.tsx
> +    ...prop
what is prop?

2023-07-20 13:04 UTC, MJyotheesh commented on src/components/input.tsx
> +      {error && <div className="error_div">{error}</div>}
don't use underscore in class  names

2023-07-20 13:07 UTC, MJyotheesh commented on src/components/styles/button.scss
> +}
styles also create one folder called generics and move these files to there

2023-07-20 13:09 UTC, MJyotheesh commented on src/pages/Home/index.tsx
> +    <div>Home coming</div>
haha

2023-07-20 13:12 UTC, MJyotheesh commented on src/shared/api/url-helper.ts
>  export const getDriversList = (params: object) => http.get('driver/get-all', params);
remove the above api

2023-07-20 13:13 UTC, MJyotheesh commented on src/shared/assets/Mask Group 2.png
change the file name without spaces

2023-07-20 13:14 UTC, MJyotheesh commented on src/shared/constant-values.ts
> +export const desktopScreen = 'https://fleetmatch-images.s3.amazonaws.com/desktop-screen.png';
except regexplist and userRole other than that anything useful here

2023-07-20 13:15 UTC, MJyotheesh commented on src/shared/formValidation/index.ts
> +export default Validate;
don't copy directly use only needful things

2023-07-20 13:21 UTC, MJyotheesh commented on src/pages/Login/index.tsx
> +        role: userRole,
no need to send role it will work

2023-07-20 13:22 UTC, MJyotheesh commented on src/pages/Login/index.tsx
remove unwanted empty lines

2023-07-20 13:23 UTC, MJyotheesh commented on src/pages/Login/index.tsx
> +      const { data = "Something Went Wrong Please Try Again" } = error;
move to constant file like services

2023-07-20 13:24 UTC, MJyotheesh commented on src/pages/Login/index.tsx
> +      alert(data);
implement notification refer supplier web

2023-07-20 13:25 UTC, MJyotheesh requested changes
Fix the comments

2023-07-20 13:41 UTC, AravindKaay commented on public/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
The earlier link code is not working . I replaced it by copying from bootstrap documentation.

2023-07-21 05:17 UTC, AravindKaay commented on src/components/styles/variables.scss
> +    --brown-shade-1: #222222;
To differentiate between different color groups as u could see black color group is separated from brown group with a space which improves readability and it doesn't look messy.

2023-07-21 10:26 UTC, MJyotheesh approved these changes

2023-07-21 10:27 UTC, merged