reduxconfig
kaaylabs-v2/fleetmatch-admin pull request #36
Opened 2023-08-21 08:24 UTC by AravindKaay

2023-08-21 09:34 UTC, Deepakkumar-kaaylabs requested changes
make sure there is no eslint error  before making PR

2023-08-21 10:12 UTC, MJyotheesh commented on src/pages/forgot-password/verification.tsx
> +  console.log(mobileView)
remove console

2023-08-21 10:12 UTC, MJyotheesh commented on src/pages/forgot-password/verification.tsx
> +  const mobileView=useSelector(mobileViewValue)
format the code properly

2023-08-21 10:15 UTC, MJyotheesh commented on src/redux/windowSlice.tsx
> +  reducers: {},
use all slicers in a single file

2023-08-21 10:17 UTC, MJyotheesh commented on src/shared/constant-values.ts
> +export const mobileViewValue = (state:RootState) => state.width.innerWidth;
??

2023-08-21 10:18 UTC, MJyotheesh commented on src/redux/windowSlice.tsx
> +  innerWidth: window.innerWidth,
don't store the value

2023-08-21 10:18 UTC, MJyotheesh commented on src/redux/windowSlice.tsx
> +  innerWidth: window.innerWidth,
just use as mobileView is true or false

2023-08-21 10:18 UTC, MJyotheesh requested changes
Resolve comments

2023-08-22 05:57 UTC, MJyotheesh commented on src/pages/forgot-password/forgot.tsx
> +          <div style={{ height: "80px" }}>
why inline

2023-08-22 06:03 UTC, MJyotheesh commented on src/pages/login/index.tsx
> +      notification("success", "login successfully");
move to const file validation messages

2023-08-22 06:04 UTC, MJyotheesh commented on src/pages/login/index.tsx
> +      if (userString.length>0) {
if (userString.length) {

2023-08-22 06:05 UTC, MJyotheesh commented on src/pages/login/index.tsx
> +      const userString = getSessionStorage("user");
change name to adminUid or adminData

2023-08-22 06:06 UTC, MJyotheesh commented on src/pages/login/index.tsx
> +    if (Object.keys(errors).length > 0) { setLoading(false); return; }
if (Object.keys(errors).length)
do we need empty return here??

2023-08-22 06:08 UTC, MJyotheesh requested changes
Resolve comments

2023-08-22 06:18 UTC, AravindKaay commented on src/pages/forgot-password/forgot.tsx
> +          <div style={{ height: "80px" }}>
I will change it (done by manohar I changed only the mobileview state here because of redux)

2023-08-22 06:22 UTC, AravindKaay commented on src/pages/login/index.tsx
> +      if (userString.length>0) {
It throws lint error bro if I change it like this

2023-08-22 07:11 UTC, AravindKaay commented on src/pages/login/index.tsx
> +    if (Object.keys(errors).length > 0) { setLoading(false); return; }
yes so that api call would not happen

2023-08-22 07:33 UTC, MJyotheesh approved these changes

2023-08-22 07:53 UTC, MJyotheesh approved these changes

2023-08-22 07:53 UTC, merged