Order request
kaaylabs-v2/fleetmatch-admin pull request #45
Opened 2023-09-06 14:20 UTC by Deepakkumar-kaaylabs

2023-09-06 16:37 UTC, MJyotheesh commented on src/shared/types.ts
> +export type TableSchemaTyeps ={
TableSchemaTypes

2023-09-06 16:39 UTC, MJyotheesh commented on src/styles/order-request.scss
don't declare colors here

2023-09-06 16:39 UTC, MJyotheesh commented on src/styles/generics/table.scss
don't declare colors here

2023-09-06 16:40 UTC, MJyotheesh commented on src/styles/generics/pagination.scss
don't declare colors here

2023-09-06 17:08 UTC, MJyotheesh commented on src/shared/icon-helper/back-arrow-icon.tsx
> +export const BackArrowIcon1 = (): JSX.Element =>
give proper name

2023-09-06 18:00 UTC, MJyotheesh commented on src/shared/types.ts
> +
start type name with capital letter like -> ResponseType

2023-09-06 18:01 UTC, MJyotheesh commented on src/shared/api/http-helper.ts
resolve lint issues

2023-09-06 18:01 UTC, MJyotheesh commented on src/shared/api/http.ts
resolve lint issues

2023-09-06 18:02 UTC, MJyotheesh commented on src/pages/routing.tsx
> +const Routing = (props: { notification: unknown }): JSX.Element => {
notification won't be unknown

2023-09-06 18:03 UTC, MJyotheesh commented on src/pages/routing.tsx
resolve lint issues

2023-09-06 18:04 UTC, MJyotheesh commented on src/pages/orders/order-request.tsx
> +          colums={tableSchema}
check spelling

2023-09-06 18:06 UTC, MJyotheesh commented on src/pages/login/index.tsx
resolve lint issues

2023-09-06 18:06 UTC, MJyotheesh commented on src/components/wrapper.tsx
> +  notification?: unknown;
it won't be unknown

2023-09-06 18:07 UTC, MJyotheesh commented on src/components/generics/title-search-component.tsx
resolve lint issues

2023-09-06 18:08 UTC, MJyotheesh commented on src/components/generics/table.tsx
> +type Itable = {
give proper type name

2023-09-06 18:10 UTC, MJyotheesh commented on src/components/generics/table.tsx
resolve lint issues don't disable lint

2023-09-06 18:11 UTC, MJyotheesh commented on src/components/generics/pagination.tsx
> +type TPagination = {
give PaginationType

2023-09-07 06:54 UTC, Deepakkumar-kaaylabs commented on src/shared/api/http-helper.ts
"strict-boolean-expressions"   can't able to solved, Can you please suggest a way for that

2023-09-07 07:55 UTC, MJyotheesh commented on src/shared/api/http-helper.ts
>    if (content) {
content != null or undefined

2023-09-07 08:01 UTC, MJyotheesh commented on src/shared/api/http-helper.ts
>    if (content) {
content != null

2023-09-07 08:02 UTC, MJyotheesh commented on src/shared/api/http-helper.ts
> +const validateSuccess = async (result: Response): responseType => {
(result: { success: boolean } & Response): ResponseType

2023-09-07 08:02 UTC, MJyotheesh commented on src/shared/api/http-helper.ts
Check below

2023-09-07 08:18 UTC, Deepakkumar-kaaylabs commented on src/components/generics/title-search-component.tsx
backIcon in the type of ReactNode so we can't able to resolve strict boolean expression

2023-09-07 09:01 UTC, MJyotheesh commented on src/components/generics/button.tsx
> +      {typeof prefix !== "undefined" && (
prefix !== undefined

2023-09-07 09:01 UTC, MJyotheesh commented on src/components/generics/button.tsx
> +      {typeof loading !== "undefined" ? (
!== undefined

2023-09-07 09:01 UTC, MJyotheesh commented on src/components/generics/button.tsx
> +      {typeof suffix !== "undefined" && (
!== undefined

2023-09-07 09:02 UTC, MJyotheesh commented on src/components/wrapper.tsx
> +  notification?: NotificationTye;
NotificationType

2023-09-07 09:19 UTC, MJyotheesh commented on src/pages/order-request/index.tsx
> +            // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
resolve this

2023-09-07 09:21 UTC, MJyotheesh commented on src/pages/order-request/index.tsx
no need separate folder for order requests move into orders folder itself

2023-09-07 09:25 UTC, MJyotheesh requested changes
Comments

2023-09-07 09:45 UTC, Deepakkumar-kaaylabs commented on src/pages/order-request/index.tsx
We have a grid and details page in order-request. so we maintain it sepratly

2023-09-07 10:44 UTC, MJyotheesh commented on src/pages/order-request/index.tsx
move it inside orders because we don't have a individual route for order request page

2023-09-07 11:32 UTC, MJyotheesh approved these changes

2023-09-07 11:32 UTC, merged