All Assets need to maintain in database and lint fix
kaaylabs-v2/fleetmatch-admin pull request #49
Opened 2023-09-13 12:04 UTC by Manoradha77

2023-09-13 13:11 UTC, MJyotheesh commented on src/shared/function-helper.ts
> +const assets =(state: RootState) => state.assets.assetsData;
format the code

2023-09-13 13:15 UTC, MJyotheesh commented on src/shared/types.ts
> +export type StrObjectType = Record<string, string>;
ObjectType was already there right use that

2023-09-13 13:16 UTC, MJyotheesh commented on src/redux/store.tsx
> +import {loginReducer,mobileViewReducer, assetReducer } from "./reduxSlice";
format the code

2023-09-13 13:16 UTC, MJyotheesh commented on src/redux/reduxSlice.tsx
> +  initialState: { assetsData: [] },
make it object

2023-09-13 13:18 UTC, MJyotheesh commented on src/pages/forgot-password/index.tsx
> +          if (formData.passWord == null) {
change passWord to password whare and all we used

2023-09-13 13:19 UTC, MJyotheesh commented on src/pages/forgot-password/index.tsx
> +          } else if (formData.confirmPassword == null) {
is this working properly?

2023-09-13 13:21 UTC, MJyotheesh requested changes
Resolve comments

2023-09-14 10:26 UTC, Manoradha77 commented on src/shared/types.ts
> +export type vehicleDetails = Record<string, any>;
If I remove this in types file then I want to change  this in vehicle details file (done by aravind have lint issues) so when he fix lint issues he will take care of this bro

2023-09-14 10:35 UTC, MJyotheesh commented on src/shared/types.ts
> +export type vehicleDetails = Record<string, any>;
okay

2023-09-14 10:35 UTC, MJyotheesh approved these changes

2023-09-14 10:36 UTC, merged